# Finish
aliveGUY/conference pull request #1
Opened 2022-04-13 17:12 UTC by aliveGUY

smth

2022-04-13 18:54 UTC, micheaol requested changes
Hi @aliveGUY , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 18:54 UTC, micheaol commented on README.md
Please ensure that the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). according to the project requirement.

2022-04-13 18:54 UTC, micheaol commented on src/pages/about.html
> -            <h1 class="pt-5" style="font-size: 16px;">"Привіт! Ділимося світом!"</h1>
Please ensure that the `navbar` looks almost identical to the original design.

1. It is divided in a top dark bar and a bottom white bar.
2. The top short bar section with social media links, logout, and language links aligned to the right.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163243341-8aad3711-12a6-4e46-ade5-40d25d6ea688.png) | ![image](https://user-images.githubusercontent.com/10332499/163243462-a6ec596c-9e26-4aa9-9f1e-589335496d5d.png)

2022-04-13 18:54 UTC, micheaol commented on src/pages/about.html
>              <p id="Headline-box" class="Headline-box p-3 mb-4">Зокрема, на цьогорічному саміті CC, заходи щодо поширення цінності обміну, вільної культури та відкритого знання з CC Чекаємо на участь
Please add a `footer` to the project according to the project requirement. Please see the example below:

Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163243978-591bbb86-af86-4307-b38d-2d0d3ec517a7.png) | ![image](https://user-images.githubusercontent.com/10332499/163244049-d0347f45-62e2-44b4-8cdb-9ff027b77eb8.png)


Please ensure you do the same on your mobile version also:
Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163244431-38cacbd3-a906-4c98-bc2d-1157ff0320b3.png) | ![image](https://user-images.githubusercontent.com/10332499/163244504-01625c7f-967b-44b7-b81b-eaba1daa5377.png)

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +      - uses: actions/checkout@v2
Please ensure to implement the `hover effect` on the `cards` according to the project requirement.
Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163245166-37df72a5-dd7a-4e71-b699-ae5a58ac0cb2.png) | ![image](https://user-images.githubusercontent.com/10332499/163245296-728bd284-2673-46ed-803d-6752fd8672f2.png)

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +          node-version: "12.x"
Please ensure that the pages look almost identical to the original design according to the project requirement.

Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163246053-7b424fef-540a-438c-a99d-b29788a6f433.png) | ![image](https://user-images.githubusercontent.com/10332499/163245952-e4bf61a9-da96-4c25-8708-63d87c09af52.png)


Please ensure you make adjustments to the mobile version. You have `text-overflow` in the mobile version.

Your Implementation |  Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163246439-bdbd76cf-f509-4c25-a70d-7d37ea41d223.png) | ![image](https://user-images.githubusercontent.com/10332499/163246582-284c45f2-a52a-4b8a-a0b7-776f5698d11c.png)


Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163246684-9e1ea53e-1187-44a2-b806-e2d4d8c564ab.png) | ![image](https://user-images.githubusercontent.com/10332499/163246795-a3b5179f-3a17-4108-a36d-5f12d00839fd.png)

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +      - uses: actions/checkout@v2
Please ensure that the pages use the exact same colors, for text, backgrounds, borders, etc, from the original design.

* Basic color swatch: #272A31, #EC5242, #D3D3D3
* Fonts used originally: Cocogoose, Lato

All page elements have similar spacing, borders, shadows, and paddings as the original design.

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +      - name: Webhint Report
Please ensure that the HTML uses semantic tags, articles use `article`,  and the footer use `footer` according to the project requirement.

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +        with:
Please ensure that the page is accessible, and images contain `alt` attributes according to the project requirement.

https://github.com/aliveGUY/conference/blob/0afac7c720b6f6c1e05c684f1c63c325b437d5a8/index.html#L16

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +      - name: Stylelint Report
Please ensure that the `speaker section` is loaded dynamically from your `javascript fille` according to the project requirement.

##### Dynamically generated HTML

1. The section "Featured speakers" is generated dynamically with JavaScript.
2. The JavaScript code is within it's own `.js` file, not inside the HTML in `script`tags.
3. The list of speakers used to generate the HTML is assigned to a variable as an array or object.
4. The list of speakers contain an speaker object for each that holds their specific data.

```
// You can use an array to store the objects
const speakerList = [ { name: "Speaker Name",... } ]
// It's ok to use an object too
const speakerList = { speaker1: { name: "Speaker Name",... } }
```

2022-04-13 18:54 UTC, micheaol commented on .github/workflows/linters.yml
> +      - uses: actions/setup-node@v1
Please ensure that there is a function that iterates through the speakers list on window load and creates HTML elements with the data from each object. 

1. The object contains all the information needed to generate the dynamic element, at least the name, role, description, and image url about the speaker. For example:

```
{
  name: "Julia Leda", 
  role: "President of Young pirates of Europe", 
  description: "European ingetration, political democracy, and participation of ...", 
  photo: "image_url_here"
}
```


For example:

```
window.onload = () => {
  speakerList.map(speaker => {
    // code to build the new HTML element, it can use `createElement()` or just template strings(``).
    // it could attach the new element to a parent inside within the loop
    // or accumulate the generate elements in a variable and attach them all after it
  })
}
```

1. The dynamic content is attached to the static HTML by selecting the target parent element and adding the generated HTML with the DOM's `appendChild()` or `innerHTML()`. For example:

```
  const speakerContainer = document.getElementById("element-id")
  ...
  speakerContainer.appendChild(dynamicElements)
  // OR
  speakerContainer.innerHTML = dynamicElements
  // If used inside a loop the innerHTML method should use `+=` instead of just `=`
```

2022-04-14 02:34 UTC, medaminedev66 requested changes
Hi @aliveGUY 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- your design was really sleek and well crafted, you'd be a great frontend engineer
- your code organization was really good.

 ## Required Changes ♻️
- [OPTIONAL] The pull Request should have a descriptive title telling others what changes are inside. It would be nicer to update that so your project is documented professionally.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 02:34 UTC, medaminedev66 commented on README.md
> +
[OPTIONAL] It would be nicer to add a description of your project to your Readme so the visitors know more about the project you worked on.

2022-04-14 02:34 UTC, medaminedev66 commented on README.md
> +# [VIDEO OF PROJECT](https://www.loom.com/share/f75adbcfb08f467bb59dfb2dca27ce0d)
- [ ] [REQUIRED] Following the project requirements, the video should contain a highlight about a piece of the code you find interesting or are proud of making.

2022-04-14 02:34 UTC, medaminedev66 commented on index.html
>              <img class="Headline-title" src="src/img/title.png" alt="title"/>
[OPTIONAL] It would be better to implement the title with `hx` and `p` tags instead of an image. It will be easier for you to change or improve the title in the future

2022-04-14 02:34 UTC, medaminedev66 commented on README.md
>  - [ ] Run `cd Portfolio` now you ready to use repo
[OPTIONAL] The MIT link is broken. Kindly fix this. Your README is the entry point of your users and having it well written without any broken links gives a good first impression and maximizes the potential of your product to your users.

2022-04-14 11:47 UTC, aliveGUY commented on index.html
>              <img class="Headline-title" src="src/img/title.png" alt="title"/>
I use images because there is no way to find the same background image for the title. I understand the importance of using <p> and other tags but I do not consider further title changes

2022-04-14 12:17 UTC, merged